// Every string the interface shows. Rules: docs/design/design-language.md §13 (checked by npm run lint:copy).
// Sentence case, no exclamation marks, no emoji, no em dashes, a verb on every button, the number wherever known.

import { plural } from '../lib/format'

export const t = {
  app: {
    name: 'OpenApplyr',
    demo: 'Sample workspace. Every company, person and job here is fictional, and nothing is sent.',
    leaveDemo: 'Leave the sample workspace',
    engineDown: 'The background engine stopped. It restarts by itself; if this stays, quit and reopen OpenApplyr.',
  },
  nav: {
    today: 'Today',
    jobs: 'Jobs',
    queue: 'Queue',
    applications: 'Applications',
    outreach: 'Outreach',
    inbox: 'Inbox',
    documents: 'Documents',
    prep: 'Prep',
    hunts: 'Hunts',
    activity: 'Activity',
    settings: 'Settings',
    collapse: 'Collapse sidebar',
    expand: 'Expand sidebar',
    assistant: 'Ask about your search',
  },
  agent: {
    running: (n: number) => (n === 1 ? 'Applying to 1 job' : `Applying to ${n} jobs`),
    working: (n: number) => plural(n, 'task running', 'tasks running'),
    idle: 'Idle',
    paused: 'Paused',
    pause: 'Pause all',
    resume: 'Resume',
    budget: (spent: string, cap: string) => `${spent} of ${cap} today`,
  },
  common: {
    selectAll: 'Select all',
    choose: 'Choose',
    selected: (n: number) => `${n} selected`,
    onePerLine: 'One per line',
    sort: 'Sort',
    mainNav: 'Main',
    notifications: 'Notifications',
    setup: 'Setup',
    moreActions: 'More actions',
    save: 'Save',
    saveChanges: 'Save changes',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    remove: 'Remove',
    edit: 'Edit',
    add: 'Add',
    retry: 'Try again',
    undo: 'Undo',
    open: 'Open',
    openPosting: 'Open posting',
    copy: 'Copy',
    copied: 'Copied',
    showDetails: 'Show details',
    hideDetails: 'Hide details',
    none: 'None',
    unknown: 'Not stated',
    yes: 'Yes',
    no: 'No',
    more: 'More actions',
    search: 'Search',
    back: 'Back',
    continue: 'Continue',
    skip: 'Skip',
    everything: 'All',
    loading: 'Loading',
    notFound: 'This item no longer exists.',
    source: 'Source',
    reveal: 'Show in folder',
  },
  status: {
    queued: 'Queued',
    applying: 'Applying',
    needs_user: 'Needs you',
    applied: 'Applied',
    applied_unverified: 'Applied, not confirmed',
    failed: 'Failed',
    screening: 'Screening',
    interviewing: 'Interviewing',
    offer: 'Offer',
    accepted: 'Accepted',
    declined: 'Declined',
    rejected: 'Rejected',
    withdrawn: 'Withdrawn',
    ghosted: 'No reply',
  } as Record<string, string>,
  today: {
    title: 'Today',
    counts: (c: { needsYou: number; appliedToday: number; repliesToday: number; matchesToday: number }) =>
      [`${c.needsYou} need you`, `${c.appliedToday} applied`, plural(c.repliesToday, 'reply', 'replies'), plural(c.matchesToday, 'new match', 'new matches')],
    needsYou: 'Needs you',
    upcoming: 'Interviews this week',
    nothing: 'Nothing needs you right now',
    nothingBody: 'Questions from applications, replies to sort and drafts to approve appear here as they come in.',
    item: {
      question: 'Waiting on your answer',
      dry_run: 'Dry run finished. Check it and send it',
      failed: 'Could not apply',
      unverified: 'Sent, but no confirmation seen',
      package: 'Ready for review',
      package_answers: (n: string) => (n === '1' ? 'Ready, 1 question needs your answer' : `Ready, ${n} questions need your answer`),
      package_failed: 'Preparation failed',
      mail: 'Reply to sort',
      outbox: 'Draft to approve',
      mail_auth: 'Email account needs signing in again',
    },
    setupTitle: 'Finish setting up',
    setup: {
      model: 'Connect a model provider',
      profile: 'Import your resume',
      hunt: 'Create your first hunt',
      mail: 'Connect your email (optional)',
    },
    setupWhy: {
      model: 'Scoring, tailoring and drafting use a model you choose, with your own key.',
      profile: 'Every tailored resume and answer is built only from your profile.',
      hunt: 'A hunt says which jobs to look for and how much to do without asking.',
      mail: 'Links replies to applications, stops follow-ups when people answer, and sends outreach from your address.',
    },
    join: 'Join',
  },
  jobs: {
    title: 'Jobs',
    views: { matches: 'Matches', new: 'New', all: 'All', saved: 'Saved', skipped: 'Skipped', filtered: 'Filtered out', applied: 'Applied' } as Record<string, string>,
    search: 'Search jobs',
    searchPlaceholder: 'Title, company or skill',
    allHunts: 'All hunts',
    importLink: 'Add a job from a link',
    importLinkLabel: 'Job posting link',
    importLinkPlaceholder: 'https://jobs.lever.co/company/1234',
    importText: 'Paste a posting instead',
    importTextLabel: 'Posting text',
    importing: 'Reading the posting',
    add: 'Add job',
    empty: 'No jobs here yet',
    emptyMatches: 'Jobs that pass a hunt\'s filters and score at or above its queue threshold appear here.',
    emptyAll: 'Jobs appear here as hunts check job boards and company career pages.',
    select: 'Select a job to see its score and posting.',
    score: 'Score',
    scoreLabel: (n: number) => `Match score ${Math.round(n)} of 100. Show breakdown.`,
    breakdown: 'How this score was worked out',
    breakdownParts: (b: { must: number; nice: number; seniority: number; domain: number }) =>
      `Must-haves ${b.must} of 70, nice-to-haves ${b.nice} of 15, level ${b.seniority} of 10, domain ${b.domain} of 5.`,
    capped: 'Capped at 40 because of a dealbreaker.',
    requirements: 'Requirements',
    niceToHave: '(nice to have)',
    seniority: { intern: 'Intern', junior: 'Junior', mid: 'Mid-level', senior: 'Senior', staff: 'Staff', principal: 'Principal', manager: 'Manager', director: 'Director', executive: 'Executive' } as Record<string, string>,
    employment: { full_time: 'Full-time', part_time: 'Part-time', contract: 'Contract', internship: 'Internship', temporary: 'Temporary' } as Record<string, string>,
    verdict: { met: 'Met', partial: 'Partly', missing: 'Missing' } as Record<string, string>,
    evidence: 'From your profile',
    notScored: 'Not scored yet',
    filteredBecause: 'Filtered out because',
    signals: 'Checks on this posting',
    posting: 'Posting',
    posted: (s: string) => `Posted ${s}`,
    seen: (s: string) => `First seen ${s}`,
    closed: 'This posting has closed.',
    prepare: 'Prepare application',
    preparing: 'Preparing',
    viewPackage: 'Open in Queue',
    save: 'Save',
    unsave: 'Unsave',
    skip: 'Skip',
    skipReasons: { level: 'Wrong level', location: 'Location', domain: 'Not my field', company: 'Company', salary: 'Salary', role: 'Wrong role', other: 'Other reason' } as Record<string, string>,
    skipped: (company: string) => `Skipped ${company}.`,
    openApplication: 'Open application',
    salary: 'Salary',
    location: 'Location',
    type: 'Type',
    company: 'Company',
    remote: { remote: 'Remote', hybrid: 'Hybrid', onsite: 'On-site', unknown: '' } as Record<string, string>,
    hideWarnings: 'Hide postings with warnings',
    sortScore: 'Best match',
    sortNewest: 'Newest',
    count: (n: number, total: number) => (n === total ? plural(total, 'job', 'jobs') : `${n} of ${plural(total, 'job', 'jobs')}`),
  },
  queue: {
    title: 'Queue',
    filters: { queue: 'Waiting', approved: 'Approved', done: 'Done' } as Record<string, string>,
    empty: 'Nothing waiting for approval',
    emptyBody: 'Jobs that pass your hunt\'s filters and reach its queue threshold (65 by default) are prepared here for you to review.',
    openHunts: 'Open hunts',
    select: 'Select a package to review it.',
    approve: 'Approve',
    approveMany: (n: number) => `Approve ${n}`,
    approvedMany: (n: number, failed: number, first: string) => `${plural(n, 'application approved', 'applications approved')}.${failed ? ` ${failed} could not be: ${first}` : ''}`,
    approveAssisted: 'Fill it, I will submit',
    approved: (company: string) => `Approved ${company}. It will be sent within its hunt's active hours.`,
    skip: 'Skip',
    regenerate: 'Prepare again',
    gates: 'Before it can go without review',
    answers: 'Form answers',
    answersFromApi: (n: number) => `${n} questions read from the application form`,
    answersCached: (n: number) => `${n} questions from an earlier application on this site`,
    answersNone: 'The form is read when the application runs. Anything new is asked then.',
    needsAnswer: (n: number) => (n === 1 ? '1 question needs your answer' : `${n} questions need your answer`),
    answerSource: { profile: 'From your profile', bank: 'Saved answer', computed: 'Worked out from your profile', generated: 'Written from your profile', user: 'Your answer', default: 'Default choice' } as Record<string, string>,
    saveFor: { no: 'This application only', all: 'Save for all applications', company: 'Save for this company' } as Record<string, string>,
    resume: 'Resume',
    coverLetter: 'Cover letter',
    noLetter: 'No cover letter for this one: the form does not take one, or the hunt is set not to write them.',
    editResume: 'Edit resume',
    compare: 'What changed from your profile',
    keywords: 'Posting keywords',
    keywordsPresent: 'In the resume',
    keywordsMissing: 'In your profile, not in this resume',
    keywordsAbsent: 'Not in your profile',
    reviewer: 'Second read',
    reviewerNone: 'No problems found.',
    cost: (c: string) => `Prepared for ${c}`,
    failed: 'Preparation failed',
    preparing: 'Preparing this application',
    status: { preparing: 'Preparing', ready: 'Ready', approved: 'Approved', skipped: 'Skipped', expired: 'Posting closed', failed: 'Failed', applied: 'Applied' } as Record<string, string>,
  },
  applications: {
    title: 'Applications',
    board: 'Board',
    table: 'Table',
    add: 'Add application',
    addTitle: 'Add an application you made elsewhere',
    import: 'Import from CSV',
    export: 'Export',
    exportCsv: 'Export CSV',
    exportJson: 'Export JSON',
    archived: 'Archived',
    showArchived: 'Show archived',
    search: 'Search applications',
    empty: 'No applications yet',
    emptyBody: 'Approved packages, and applications you add by hand, are tracked here from first click to offer.',
    columns: { active: 'In progress', applied: 'Applied', screening: 'Screening', interviewing: 'Interviewing', offer: 'Offer', closed: 'Closed' } as Record<string, string>,
    moveTo: 'Move to',
    setStatus: 'Set status',
    archive: 'Archive',
    unarchive: 'Restore',
    runAgain: 'Run again',
    sendForReal: 'Send it',
    fillForMe: 'Fill it, I will submit',
    markApplied: 'Mark as applied',
    timeline: 'Timeline',
    documents: 'Documents used',
    evidence: 'Evidence',
    evidenceNone: 'Screenshots and the filled fields are saved here when an application runs.',
    runs: 'Runs',
    notes: 'Notes',
    notesPlaceholder: 'Who you spoke to, what they said, what to follow up on',
    contacts: 'People',
    findPeople: 'Find people',
    interviews: 'Interviews',
    addInterview: 'Add interview',
    offer: 'Offer',
    applied: (s: string) => `Applied ${s}`,
    via: { agent: 'Sent by OpenApplyr', assisted: 'Filled by OpenApplyr, sent by you', manual: 'Added by hand' } as Record<string, string>,
    confirmation: 'Confirmation',
    fields: { company: 'Company', title: 'Job title', url: 'Posting link', status: 'Status', appliedOn: 'Applied on', channel: 'How you applied', notes: 'Notes', lastActivity: 'Last activity', hunt: 'Hunt' },
    channels: { ats: 'Company careers site', email: 'Email', referral: 'Referral', other: 'Other' } as Record<string, string>,
    event: {
      created: 'Added',
      approved: 'Approved',
      run_started: 'Run started',
      applied: 'Applied, confirmation seen',
      applied_unverified: 'Sent, no confirmation seen',
      needs_user: 'Waiting on you',
      dry_run: 'Dry run finished',
      run_failed: 'Run failed',
      stopped: 'Stopped',
      closed: 'Posting closed',
      status: 'Status changed',
      email: 'Email',
      interview: 'Interview scheduled',
      outreach_sent: 'Email sent',
      note: 'Note added',
      archived: 'Archived',
      unarchived: 'Restored',
    } as Record<string, string>,
    source: { user: 'you', app: 'OpenApplyr', run: 'the application run', mail: 'your email', import: 'import', rule: 'a rule' } as Record<string, string>,
    importTitle: 'Import applications',
    importBody: 'Choose a CSV exported from a spreadsheet, Teal or Huntr. Columns are matched by name; check them before importing.',
    importChoose: 'Choose CSV file',
    importColumn: (f: string) => f,
    importRun: (n: number) => `Import ${plural(n, 'row', 'rows')}`,
    importDone: (r: { imported: number; skipped: number; duplicates: number }) =>
      `Imported ${r.imported}. Skipped ${r.skipped} saved-only rows and ${r.duplicates} already here.`,
    importField: { company: 'Company', title: 'Job title', status: 'Status', appliedAt: 'Date applied', url: 'Link', location: 'Location', notes: 'Notes' } as Record<string, string>,
    notMapped: 'Not imported',
    analytics: 'Results',
  },
  analytics: {
    title: 'Results',
    range: { '30d': 'Last 30 days', '90d': 'Last 90 days', all: 'All time' } as Record<string, string>,
    funnel: 'Funnel',
    stages: { applied: 'Applied', responded: 'Any response', screen: 'Screen', interview: 'Interview', offer: 'Offer' } as Record<string, string>,
    of: (n: number, d: number) => `${n} of ${d}`,
    median: (d: number | null) => (d === null ? 'No responses yet' : `Median ${d} days to first response`),
    ghosted: (n: number, d: number) => `${n} of ${d} got no reply`,
    byChannel: 'Response rate by how you applied',
    byTemplate: 'By resume template',
    byDays: 'By days after posting',
    byHunt: 'By hunt',
    byTitle: 'By title',
    weekly: 'Last 12 weeks',
    weeklyApplied: 'Applied',
    weeklyResponses: 'Responses',
    spend: 'Model spend',
    spendTotal: (s: string) => `${s} in this period`,
    spendPer: (s: string) => `${s} per application`,
    notes: 'What is working',
    notesEmpty: 'Comparisons appear once each group has at least 20 applications.',
    group: 'Group',
    applied: 'Applied',
    responded: 'Responded',
    rate: 'Rate',
  },
  outreach: {
    title: 'Outreach',
    tabs: { drafts: 'Drafts', scheduled: 'Scheduled', sent: 'Sent', contacts: 'People' } as Record<string, string>,
    empty: 'No drafts to approve',
    emptyBody: 'When a hunt has outreach on, notes to recruiters and hiring managers are drafted here after each application goes out.',
    emptyScheduled: 'Nothing scheduled',
    emptySent: 'Nothing sent yet',
    select: 'Select a message to read or edit it.',
    to: 'To',
    subject: 'Subject',
    body: 'Message',
    attachResume: 'Attach the tailored resume',
    approve: 'Approve and schedule',
    approveMany: (n: number) => `Approve ${n}`,
    sendNow: 'Send now',
    cancel: 'Cancel sequence',
    sendConfirm: (name: string) => `Send this email to ${name} now from your mailbox?`,
    step: (n: number) => (n === 0 ? 'First message' : `Follow-up ${n}`),
    scheduledFor: (s: string) => `Scheduled for ${s}`,
    sentAt: (s: string) => `Sent ${s}`,
    followUps: (n: number) => plural(n, 'follow-up', 'follow-ups'),
    purpose: { recruiter_intro: 'Note to a recruiter', hiring_manager: 'Note to the hiring manager', referral: 'Referral request', follow_up: 'Follow-up', thank_you: 'Thank you', linkedin_note: 'LinkedIn connection note', linkedin_message: 'LinkedIn message' } as Record<string, string>,
    draftNew: 'Draft a message',
    drafting: 'Drafting',
    issues: 'Check before sending',
    emailStatus: { verified: 'Verified address', likely: 'Likely address', guessed: 'Guessed from the company pattern', unknown: 'Address not checked' } as Record<string, string>,
    noMail: 'Connect an email account in Settings to send.',
    contacts: {
      search: 'Search people',
      add: 'Add person',
      empty: 'No people yet',
      emptyBody: 'Recruiters and hiring managers found for your applications are listed here. You can add people by hand too.',
      doNotContact: 'Do not contact',
      allowContact: 'Allow contact again',
      blocked: 'Asked not to be contacted',
      lastContacted: (s: string) => `Last contacted ${s}`,
      relation: { recruiter: 'Recruiter', hiring_manager: 'Hiring manager', team: 'Team member', generic: 'Company inbox', other: 'Other' } as Record<string, string>,
      fields: { name: 'Name', title: 'Job title', email: 'Email', linkedin: 'LinkedIn profile', company: 'Company', notes: 'Notes' },
    },
  },
  inbox: {
    title: 'Inbox',
    filters: { review: 'To sort', linked: 'Linked', all: 'All' } as Record<string, string>,
    empty: 'Nothing to sort',
    emptyBody: 'Replies that could belong to more than one application, or that OpenApplyr is unsure about, wait here.',
    emptyAll: 'No job email yet',
    emptyAllBody: 'Confirmations, replies, invites and rejections appear here once an email account is connected. Other mail is never stored.',
    connect: 'Connect email',
    select: 'Select a message to read it.',
    loadingBody: 'Fetching the message from your mail server',
    linkTo: 'Belongs to',
    notLinked: 'Not linked to an application',
    suggestions: 'Possible matches',
    confirm: 'Link it',
    confirmAndSet: (s: string) => `Link it and mark ${s.toLowerCase()}`,
    dismiss: 'Not about an application',
    category: {
      application_received: 'Confirmation',
      rejection: 'Rejection',
      interview_request: 'Interview request',
      assessment: 'Assessment',
      offer: 'Offer',
      recruiter_outreach: 'Recruiter',
      positive_reply: 'Positive reply',
      negative_reply: 'Negative reply',
      neutral_reply: 'Reply',
      out_of_office: 'Out of office',
      verification_code: 'Verification code',
      scheduling: 'Scheduling',
      other: 'Other',
    } as Record<string, string>,
    code: 'Code',
    syncNow: 'Check now',
    lastSync: (s: string) => `Checked ${s}`,
  },
  documents: {
    title: 'Documents',
    tabs: { profile: 'Profile', resumes: 'Resumes', answers: 'Saved answers', voice: 'Writing voice' } as Record<string, string>,
    base: 'Base resumes',
    tailored: 'Tailored resumes',
    createBase: 'Create base resume',
    noResumes: 'No resumes yet',
    noResumesBody: 'A base resume is built from your profile. Tailored copies are made for each application you approve.',
    template: 'Template',
    pageSize: 'Page size',
    pageSizes: { Letter: 'US Letter', A4: 'A4' } as Record<string, string>,
    preview: 'Preview',
    atsCheck: 'Parser check',
    atsBody: 'The PDF read back as an applicant tracking system reads it.',
    atsRun: 'Check the PDF',
    exportPdf: 'Export PDF',
    exportDocx: 'Export Word',
    exportTxt: 'Export text',
    critique: 'Get a second read',
    critiqueRunning: 'Reading the resume',
    edit: 'Edit content',
    headline: 'Headline',
    summary: 'Summary',
    skills: 'Skills',
    skillsHelp: 'Separate with commas, most relevant first.',
    flagged: 'Reverted to your wording: the tailored line did not match your profile.',
    deleteResume: 'Delete resume',
    setDefault: 'Use for new hunts',
    answers: {
      search: 'Search saved answers',
      empty: 'No saved answers yet',
      emptyBody: 'Answers you give on application forms can be saved here and reused on the next form that asks the same thing.',
      company: (c: string | null) => (c ? `For ${c} only` : 'All companies'),
      used: (n: number) => plural(n, 'use', 'uses'),
    },
    voice: {
      title: 'Writing voice',
      body: 'Paste two or three things you wrote yourself, such as emails or a LinkedIn about section. Drafts of letters and emails follow the description below; you can edit it directly.',
      samples: 'Writing samples',
      description: 'Voice description',
      describe: 'Describe my writing',
      describing: 'Reading your samples',
    },
  },
  profile: {
    title: 'Profile',
    importTitle: 'Import your resume',
    importBody: 'PDF, Word, text, JSON Resume or a LinkedIn data export (the ZIP from Settings, Data privacy). Nothing is uploaded anywhere except to the model provider you chose, to read it.',
    choose: 'Choose file',
    paste: 'Paste resume text',
    pasteLabel: 'Resume text',
    reading: 'Reading your resume',
    checkThese: 'These lines were not found in the file. Check them before saving.',
    completeness: 'What applications will ask for',
    basics: 'Contact',
    work: 'Experience',
    education: 'Education',
    skills: 'Skills',
    search: 'Job search facts',
    searchWhy: 'Application forms ask these. Legal and salary questions are only ever answered from here or from answers you saved.',
    fields: {
      name: 'Full name',
      email: 'Email',
      phone: 'Phone',
      city: 'City',
      region: 'Region or state',
      country: 'Country code',
      countryHelp: 'Two letters, for example PT, US, GB.',
      headline: 'Headline',
      summary: 'Summary',
      links: 'Links',
      company: 'Company',
      jobTitle: 'Title',
      start: 'Start',
      end: 'End',
      current: 'I work here now',
      location: 'Location',
      bullets: 'What you did',
      bulletsHelp: 'One line per result. Numbers you write here are the only numbers tailored resumes can use.',
      institution: 'School',
      degree: 'Degree',
      field: 'Field of study',
      skill: 'Skills',
      skillHelp: 'Separate with commas.',
      noticePeriod: 'Notice period',
      earliestStart: 'Earliest start date',
      expected: 'Expected salary per year',
      currency: 'Currency',
      relocation: 'Open to relocating',
      over18: '18 or older',
      driversLicense: 'Driving licence',
      clearance: 'Security clearance',
      clearanceHelp: 'Leave empty if you have none.',
      travel: 'Willing to travel',
      workAuth: 'Work authorization',
      authCountry: 'Country',
      authorized: 'Authorized to work',
      sponsorship: 'Needs sponsorship',
      addCountry: 'Add country',
      eeo: 'Voluntary self-identification',
      eeoHelp: 'Left empty, these are answered "Decline to self-identify". They are never guessed.',
      eeoFields: { gender: 'Gender', race: 'Race or ethnicity', hispanic: 'Hispanic or Latino', veteran: 'Veteran status', disability: 'Disability status', pronouns: 'Pronouns' } as Record<string, string>,
    },
    relocation: { yes: 'Yes', no: 'No', maybe: 'Ask each time' } as Record<string, string>,
    addRole: 'Add role',
    addEducation: 'Add education',
    addLine: 'Add line',
    present: 'Present',
    saved: 'Profile saved.',
    years: (y: number) => `${Math.floor(y)} years of experience`,
  },
  prep: {
    title: 'Prep',
    tabs: { interviews: 'Interviews', practice: 'Practice', stories: 'Stories', offers: 'Offers', career: 'Career tools' } as Record<string, string>,
    noInterviews: 'No interviews scheduled',
    noInterviewsBody: 'Invites that arrive by email appear here with their time and link. You can add interviews by hand too.',
    addInterview: 'Add interview',
    interviewKind: { recruiter: 'Recruiter screen', technical: 'Technical', behavioral: 'Behavioral', onsite: 'Onsite', final: 'Final', other: 'Other' } as Record<string, string>,
    prepFor: (c: string) => `Prep for ${c}`,
    brief: 'Company brief',
    briefMake: 'Write the brief',
    briefWriting: 'Reading the posting and the company\'s pages',
    briefNone: 'A short brief from the posting and the company\'s own pages, with a source on every point.',
    questions: 'Likely questions',
    questionsMake: 'List likely questions',
    questionsWriting: 'Reading the requirements',
    ask: 'Questions to ask them',
    checklist: 'Before the interview',
    why: 'Why they ask',
    join: 'Join',
    fields: { application: 'Application', when: 'Date and time', duration: 'Length in minutes', kind: 'Type', link: 'Meeting link', location: 'Place', interviewers: 'Interviewers', interviewersHelp: 'Separate names with commas.', notes: 'Notes' },
    practice: {
      start: 'Start practice',
      kind: 'Interview type',
      forApp: 'For application',
      general: 'General practice',
      answer: 'Your answer',
      answerPlaceholder: 'Answer as you would out loud',
      send: 'Send answer',
      thinking: 'Reading your answer',
      stronger: 'A stronger version, from your facts',
      scores: { structure: 'Structure', specificity: 'Specificity', relevance: 'Relevance', length: 'Length' } as Record<string, string>,
      empty: 'No practice sessions yet',
      emptyBody: 'Practice with an interviewer for a real application, and get feedback on each answer.',
    },
    stories: {
      empty: 'No stories yet',
      emptyBody: 'Interview stories in the situation, task, action and result shape, drafted from your work history for you to edit.',
      draft: 'Draft stories from my profile',
      drafting: 'Drafting stories',
      add: 'Add story',
      fields: { title: 'Title', situation: 'Situation', task: 'Task', action: 'Action', result: 'Result', tags: 'Tags' },
    },
    offers: {
      empty: 'No offers yet',
      emptyBody: 'Add an offer to compare pay over the vesting period and draft a reply.',
      add: 'Add offer',
      compare: 'Compare',
      firstYear: 'First year',
      averageYear: 'Average year',
      negotiate: 'Draft a counter-offer',
      target: 'What you are asking for',
      targetPlaceholder: '€92,000 base',
      drafting: 'Drafting',
      fields: { company: 'Company', title: 'Job title', currency: 'Currency', base: 'Base salary', bonus: 'Bonus (% of base)', signOn: 'Sign-on bonus', equity: 'Equity value (total)', vesting: 'Vesting years', cliff: 'Cliff in months', benefits: 'Benefits', location: 'Location', deadline: 'Reply by' },
    },
    career: {
      gap: 'Skills gap',
      gapBody: (jobs: number) => `Requirements you are missing, across ${plural(jobs, 'recently scored job', 'recently scored jobs')}.`,
      gapRow: (m: number, j: number) => `missing in ${m} of ${j}`,
      gapEmpty: 'Scores from the last 60 days show here once jobs have been scored.',
      explore: 'Nearby titles',
      exploreBody: 'Titles in your local job database whose postings ask for things your profile shows.',
      exploreEmpty: 'Needs more postings in the local database. It fills as hunts run.',
      youHave: 'You have',
      youLack: 'Often asked, not in your profile',
      post: 'LinkedIn post',
      postTopic: 'What the post is about',
      postPlaceholder: 'What I learned moving batch jobs to event-driven workers',
      postWrite: 'Draft post',
    },
  },
  hunts: {
    title: 'Hunts',
    new: 'New hunt',
    empty: 'No hunts yet',
    emptyBody: 'A hunt describes the jobs you want and how much OpenApplyr may do on its own.',
    select: 'Select a hunt to edit it.',
    name: 'Name',
    active: 'Active',
    paused: 'Paused',
    stats: (s: { matched: number; queued: number; appliedToday: number }) => `${s.matched} matched, ${s.queued} waiting, ${s.appliedToday} applied today`,
    sections: { what: 'What to look for', where: 'Where', filters: 'Filters', mode: 'How much to do on its own', documents: 'Documents', outreach: 'Outreach', limits: 'Limits' },
    titles: 'Job titles',
    titlesHelp: 'One per line. Word order and level words ("senior") do not matter.',
    titlesPlaceholder: 'Backend engineer',
    suggestTitles: 'Suggest related titles',
    exclude: 'Exclude words',
    excludeHelp: 'Jobs whose title contains any of these are filtered out. One per line.',
    places: 'Places',
    placesHelp: 'City and distance for on-site and hybrid roles.',
    addPlace: 'Add place',
    radius: 'Within km',
    workplace: 'Workplace',
    remoteCountries: 'Remote roles open to',
    remoteCountriesHelp: 'Country codes, comma separated. Empty means your own country.',
    employment: 'Employment type',
    seniority: 'Level',
    seniorityHelp: 'Empty means any level.',
    salaryFloor: 'Minimum salary per year',
    includeUnknownSalary: 'Include jobs without a posted salary',
    companiesInclude: 'Only these companies',
    companiesExclude: 'Never these companies',
    excludeStaffing: 'Skip staffing agencies',
    requireSponsorship: 'I need visa sponsorship',
    postedWithin: 'Posted within days',
    queueThreshold: 'Prepare jobs scoring at least',
    autopilotThreshold: 'Send without review from',
    mode: 'Mode',
    modes: {
      manual: 'Manual: find and score jobs; you choose, OpenApplyr fills forms, you submit',
      review: 'Review: prepare applications; each one waits for your approval',
      autopilot: 'Autopilot: send applications that pass every check; the rest wait for you',
    } as Record<string, string>,
    generatedAnswers: 'In autopilot, send written answers without review',
    activeHours: 'Apply between',
    dailyCap: 'Applications per day',
    cooldown: 'At most',
    cooldownDays: 'per company every',
    days: 'days',
    coverLetter: 'Cover letters',
    coverLetterOptions: { always: 'Always', when_accepted: 'When the form takes one', never: 'Never' } as Record<string, string>,
    template: 'Resume template',
    reviewer: 'Second read of each tailored resume',
    baseResume: 'Base resume',
    outreachEnabled: 'Find a recruiter or hiring manager and draft a note after each application',
    outreachAutopilot: 'In autopilot, send notes without review',
    outreachCap: 'Notes per day',
    followUps: 'Follow up after business days',
    preview: 'Preview',
    previewCount: (pass: number, total: number) => `${pass} of ${total} jobs in your database pass these filters`,
    runNow: 'Search now',
    delete: 'Delete hunt',
    suggestions: 'Suggestions from your skips',
    applySuggestion: 'Apply',
    saved: 'Hunt saved.',
  },
  activity: {
    title: 'Activity',
    tabs: { runs: 'Application runs', tasks: 'Background work', sources: 'Job sources', spend: 'Model spend' } as Record<string, string>,
    noRuns: 'No application runs yet',
    noRunsBody: 'Each application OpenApplyr fills is recorded here step by step, with screenshots.',
    run: {
      mode: { submit: 'Submit', dry_run: 'Dry run', assisted: 'You submit' } as Record<string, string>,
      status: { running: 'Running', needs_user: 'Needs you', submitted: 'Submitted', ready: 'Filled', failed: 'Failed', stopped: 'Stopped', paused: 'Paused', dry_run_done: 'Dry run done' } as Record<string, string>,
      stop: 'Stop run',
      continue: 'Continue',
      answer: 'Answer',
      answerLabel: 'Your answer',
      saveAnswer: 'Save it for next time',
      steps: 'Steps',
      evidence: 'Evidence',
    },
    tasksEmpty: 'Nothing running',
    openApplication: 'Open application',
    adapters: { greenhouse: 'Greenhouse', lever: 'Lever', ashby: 'Ashby', workday: 'Workday', smartrecruiters: 'SmartRecruiters', workable: 'Workable', recruitee: 'Recruitee', generic: 'Other site' } as Record<string, string>,
    retry: 'Retry',
    sources: { name: 'Source', kind: 'Type', jobs: 'Jobs', lastOk: 'Last checked', problem: 'Problem', onlyProblems: 'Only sources with problems' },
    spend: { when: 'When', model: 'Model', task: 'Task', tokens: 'Tokens', cost: 'Cost', unpriced: 'No price known' },
  },
  settings: {
    title: 'Settings',
    tabs: { models: 'Models', email: 'Email', integrations: 'Connected services', applying: 'Applying', notifications: 'Notifications', general: 'General', data: 'Data and privacy', about: 'About' } as Record<string, string>,
    models: {
      providers: 'Providers',
      providersBody: 'Scoring, tailoring and drafting run on a model you choose, billed to your own account. Keys stay encrypted on this computer.',
      add: 'Add provider',
      addTitle: 'Add a model provider',
      kind: 'Provider',
      test: 'Test connection',
      testing: 'Testing',
      testOk: (ms: number, model: string) => `Connected to ${model} in ${ms} ms.`,
      refresh: 'Refresh models',
      local: 'Look for local models',
      roles: 'Which model does what',
      rolesBody: 'A small, fast model is enough for scoring and sorting mail. Writing benefits from a stronger one.',
      role: { fast: 'Scoring and sorting', writer: 'Resumes, letters and emails', agent: 'Filling unusual forms', review: 'Second read' } as Record<string, string>,
      autoAssign: 'Pick for me',
      budget: 'Budget',
      budgetBody: 'Work stops when a limit is reached, and resumes the next day or month.',
      daily: 'Per day (USD)',
      monthly: 'Per month (USD)',
      spent: (today: string, month: string) => `Spent ${today} today and ${month} this month.`,
      prices: 'Prices',
      noProviders: 'No provider connected',
      noProvidersBody: 'Add one to start scoring jobs. Anthropic, OpenAI, Google and many others work, as does a model running on this computer.',
      remove: 'Remove provider',
      price: (i: number, o: number) => `$${i} in, $${o} out per million tokens`,
      free: 'No charge',
      noPrice: 'No price known',
      modelCount: (n: number) => (n === 1 ? '1 model' : `${n} models`),
    },
    email: {
      accounts: 'Accounts',
      body: 'Replies, confirmations and invites are read to update your applications. Only job-related mail is stored, as a short snippet. Outreach is sent from your own address.',
      add: 'Connect email',
      addTitle: 'Connect an email account',
      provider: 'Provider',
      address: 'Email address',
      password: 'App password',
      passwordHelp: 'A separate password made for OpenApplyr, not your account password.',
      makePassword: 'Create an app password',
      signIn: 'Sign in with Microsoft',
      clientId: 'Application (client) ID',
      clientIdHelp: 'Microsoft requires each installation to use an app registration. Register a free one (public client, redirect http://127.0.0.1) and paste its ID.',
      googleClient: 'Use my own Google client instead',
      imapHost: 'IMAP server',
      smtpHost: 'SMTP server',
      port: 'Port',
      tls: 'TLS',
      displayName: 'Name on sent mail',
      connecting: 'Signing in to both servers',
      dailyCap: 'Emails per day',
      disconnect: 'Disconnect',
      sync: 'Check now',
      status: { ok: 'Connected', error: 'Last check failed', auth_error: 'Needs signing in again' } as Record<string, string>,
      none: 'No email connected',
    },
    integrations: {
      body: 'Optional keys for more job boards and for finding contact addresses. Each is billed by, and belongs to, you.',
      connect: 'Connect',
      disconnect: 'Disconnect',
      connected: 'Connected',
      getKey: 'Get a key',
    },
    applying: {
      browser: 'Browser',
      browserBody: 'Applications are filled in a separate browser profile, so your own logins and history are never touched.',
      browserChoice: { auto: 'Chrome or Edge, whichever is installed', chrome: 'Google Chrome', msedge: 'Microsoft Edge', chromium: 'Chromium', custom: 'Another browser' } as Record<string, string>,
      browserPath: 'Browser program',
      headless: 'Fill forms without showing the browser window',
      pace: 'Pace',
      globalCap: 'Applications per day, all hunts',
      gap: 'Seconds between applications',
      hostGap: 'Seconds between applications on the same site',
      trust: 'Dry runs left',
      trustBody: 'The first applications stop before the final click so you can see exactly what was filled.',
      waitMinutes: 'Minutes to wait for your answer before pausing a run',
    },
    notifications: {
      needsYou: 'When an application needs you',
      replies: 'Replies and interview requests',
      matches: 'New strong matches (at most every 2 hours)',
      evening: 'Evening summary',
      quiet: 'Quiet hours',
      from: 'From',
      until: 'Until',
    },
    general: {
      theme: 'Theme',
      themes: { system: 'Match the system', light: 'Light', dark: 'Dark' } as Record<string, string>,
      density: 'Row height',
      densities: { compact: 'Compact', comfortable: 'Comfortable' } as Record<string, string>,
      region: 'Region',
      regionHelp: 'Sets the default resume template, page size and spelling.',
      regions: { US: 'United States', CA: 'Canada', UK: 'United Kingdom', EU: 'Europe', IN: 'India', AU: 'Australia', OTHER: 'Elsewhere' } as Record<string, string>,
      background: 'Keep running in the background when the window is closed',
      login: 'Open at login',
    },
    data: {
      folder: 'Data folder',
      reveal: 'Show data folder',
      backup: 'Back up now',
      backedUp: (p: string) => `Backup saved to ${p}`,
      export: 'Export everything',
      exportBody: 'A folder with your profile, applications as CSV and JSON, documents, evidence and a copy of the database. API keys and passwords are left out.',
      delete: 'Delete all data',
      deleteBody: 'Removes every application, document, saved answer, key and email copy from this computer. This cannot be undone.',
      deleteConfirm: 'Type DELETE to confirm',
      deleteRun: 'Delete everything',
      privacy: 'Contact details are stripped from anything sent for scoring',
    },
    about: {
      version: (v: string) => `Version ${v}`,
      license: 'Open source under the GNU AGPL 3.0.',
      source: 'Source code',
      issues: 'Report a problem',
      credits: 'Fonts: IBM Plex and Libre Baskerville (SIL Open Font License). Place names: GeoNames (CC BY 4.0).',
    },
  },
  onboarding: {
    steps: { model: 'Model', profile: 'Resume', facts: 'Facts', hunt: 'Hunt', email: 'Email' } as Record<string, string>,
    modelTitle: 'Choose the model that does the reading and writing',
    modelBody: 'Use your own key from any major provider, or a model running on this computer. Costs go to your account; set a budget in Settings.',
    profileTitle: 'Import your resume',
    factsTitle: 'The facts forms ask for',
    factsBody: 'Legal, salary and eligibility questions are only ever answered from what you enter here.',
    huntTitle: 'What should OpenApplyr look for',
    emailTitle: 'Connect your email',
    emailBody: 'Optional. Lets OpenApplyr link replies and invites to applications, stop follow-ups when someone answers, and send notes from your address.',
    emailSkip: 'Do this later',
    next: 'Continue',
    finish: 'Start the first search',
    sample: 'Explore a sample workspace first',
    parsed: (roles: number, skills: number, schools: number) => `${plural(roles, 'role', 'roles')}, ${plural(skills, 'skill', 'skills')}, ${plural(schools, 'school', 'schools')}`,
  },
  unlock: {
    title: 'Unlock OpenApplyr', // copy-ok: literal action
    firstTitle: 'Set a passphrase',
    body: 'This system has no secure key store, so your saved keys and passwords are protected with a passphrase you choose.',
    passphrase: 'Passphrase',
    unlock: 'Unlock', // copy-ok: the literal action on the passphrase screen
    setUp: 'Set passphrase',
    wrong: 'That passphrase did not unlock the data. Check it and try again.', // copy-ok: literal, not marketing
  },
  palette: {
    label: 'Go to or do',
    placeholder: 'Type a screen, a job, a company or an action',
    goTo: (s: string) => `Go to ${s}`,
    none: 'No match',
  },
  assistant: {
    title: 'Ask about your search',
    placeholder: 'How many applications got a reply this month?',
    send: 'Ask',
    thinking: 'Looking through your data',
    newChat: 'New conversation',
    empty: 'Answers come from your own applications, jobs and email. It can add notes and propose changes; it never sends or applies.',
    proposal: 'Proposed hunt change',
    apply: 'Apply change',
    draftRequest: 'Draft requested',
    openOutbox: 'Open drafts',
    noteAdded: 'Note added',
  },
  errors: {
    generic: (msg: string) => msg,
    offline: 'Could not reach the engine. Retrying.',
  },
}
